- name: Check that the reboot-requied exists
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Automated reboot
  reboot:
  when:
    - reboot_required_file.stat.exists == true
